env:
  global:
    - CI_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=13Khc0R4Pmlt8L1YImqasl0q7lDR5g0XY

language: java
jdk:
  - oraclejdk8          // tells Travis to use Java 8

after_success:
  - gradle jacocoTestReport coveralls
